const languages = [
    { label: "Arabic", value: "ar" },
    { label: "Azerbaijani", value: "az" },
    { label: "Bulgarian", value: "bg" },
    { label: "Bengali", value: "bn" },
    { label: "Catalan", value: "ca" },
    { label: "Czech", value: "cs" },
    { label: "Danish", value: "da" },
    { label: "German", value: "de" },
    { label: "Greek", value: "el" },
    { label: "English", value: "en" },
    { label: "Esperanto", value: "eo" },
    { label: "Spanish", value: "es" },
    { label: "Estonian", value: "et" },
    { label: "Basque", value: "eu" },
    { label: "Persian", value: "fa" },
    { label: "Finnish", value: "fi" },
    { label: "French", value: "fr" },
    { label: "Irish", value: "ga" },
    { label: "Galician", value: "gl" },
    { label: "Hebrew", value: "he" },
    { label: "Hindi", value: "hi" },
    { label: "Hungarian", value: "hu" },
    { label: "Indonesian", value: "id" },
    { label: "Italian", value: "it" },
    { label: "Japanese", value: "ja" },
    { label: "Korean", value: "ko" },
    { label: "Lithuanian", value: "lt" },
    { label: "Latvian", value: "lv" },
    { label: "Malay", value: "ms" },
    { label: "Norwegian", value: "nb" },
    { label: "Dutch", value: "nl" },
    { label: "Polish", value: "pl" },
    { label: "Portuguese", value: "pt" },
    { label: "Romanian", value: "ro" },
    { label: "Russian", value: "ru" },
    { label: "Slovak", value: "sk" },
    { label: "Slovenian", value: "sl" },
    { label: "Albanian", value: "sq" },
    { label: "Serbian", value: "sr" },
    { label: "Swedish", value: "sv" },
    { label: "Thai", value: "th" },
    { label: "Tagalog", value: "tl" },
    { label: "Turkish", value: "tr" },
    { label: "Ukrainian", value: "uk" },
    { label: "Urdu", value: "ur" },
    { label: "Vietnamese", value: "vi" },
    { label: "Chinese", value: "zh" },
    { label: "Chinese (traditional)", value: "zt" },
];

export default languages;
